@startuml
!include style.puml
allowmixing

Package " "<<Rectangle>>{
    Class UI
    Class Parser
    Class MovieMate
    Class Movie
    Class Storage
}

Actor User

'MovieMate handles all of this!'
MovieMate --> UI
MovieMate --> Parser
MovieMate --> Movie
MovieMate --> Storage

User .right.> UI
UI ..> Parser


@enduml