@startuml
!include ../Style.puml

'review1, class diagram'
actor User

participant Review COLOR_MOVIE
User -> Review
activate Review

Review -> Scanner : setReview()
activate Scanner
Scanner --> Scanner : new Scanner(input)


loop COLOR_BLOCK input not empty

    Scanner -> User
    User --> Scanner : Input
end
deactivate Scanner

Scanner --> Review : return input
Review -> Review : set reviewText

Review -> Scanner : get numerical input

loop input not between 0 to 5
    Scanner -> User
    User --> Scanner : input
end

Scanner --> Review : return input

Review -> Review : set reviewStars

Review --> User : feedback
@enduml
